config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#index'
  get 'pages/help'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/search', to: 'topics#search'
  
  # post 'topics/update' , to: 'topics#update', as: 'topics_update'
  
  resources :users
  
  resources :topics do
    collection do
      post :ajax_gram
    end
  end
  
  # resources :favorites
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  # コメント実装
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/material.rb
class Material < ApplicationRecord
  
  # validates :user_id, presence: true
  validates :material, presence: true
  validates :gram, presence: true
  
    # 複数入れ子
  belongs_to :topic
    
  
  def reject_both_blank(attributes)
    if attributes[:id]
      attributes.merge!(_destroy: "1") if attributes[:face].blank? and attributes[:flip].blank?
      !attributes[:face].blank? and attributes[:flip].blank?
    else
      attributes[:face].blank? and attributes[:flip].blank?
    end
  end
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :title, presence: true
  
  belongs_to :user
  
  # 複数入れ子
  has_many :materials,dependent: :destroy
  
  has_many :material_topics, through: :materials, source: 'topic'
  
  accepts_nested_attributes_for :materials
  
  mount_uploader :image, ImageUploader
  
  has_many :favorites,dependent: :destroy
  has_many :favorite_users, through: :favorites, source: 'user'
  # コメント実装トピックに関連
  has_many :comments,dependent: :destroy
  has_many :comemnt_users, through: :comments, source: 'user'
  
  def self.search(search)
      if search
        Topic.where(['title LIKE ?', "%#{search}%"])
      else
        Topic.all
      end
  end
    
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 }

  EMAIL_REGEX = /[a-zA-Z0-9._+]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*/
  validates :email, presence: true, format: { with: EMAIL_REGEX }

  validates :password, length: { in: 8..32 }

  PW_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\z/i
  validates :password, presence: true, format: { with: PW_REGEX }

  has_secure_password
  
  has_many :topics
  
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  # コメント実装ユーザーに関連
  has_many :comments
  has_many :comment_topics, through: :comments, source: 'topic'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
  
   helper_method :current_user,:logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @Comment_topics = current_user.comment_topics
    @comment = Comment.find_by(topic_id: topic_id)
  end
  
  def new
    @comment = Comment.new
    @comment.topic_id = params[:topic_id]
  end
  
  def create
    @comment = current_user.comments.new(comment_params)
    # @comment.user_id = current_user.id
    
    if @comment.save
        redirect_to topics_path, success: 'コメントしました'
    else
        redirect_to topics_path, danger: 'コメントに失敗しました'
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:content,:topic_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  # indexは一覧表示　current_user.favorite_topics＝自分のuserのfavorite_topics
  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    
    
    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
    end
  end
  
  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    @favorite.destroy
    redirect_to topics_path, success: 'いいねを取り消しました'
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
     @topics = Topic.all.includes(:favorite_users)
    # 投稿順入れ替え
    @topics = Topic.all.order(created_at: :desc).limit(5)
  end
  
  def helpe
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email_params)
    if user && user.authenticate(password_params[:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def email_params
    params.require(:session).permit(:email)
  end
  def password_params
    params.require(:session).permit(:password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all.includes(:favorite_users)
    # 投稿順入れ替え
    @topics = Topic.all.order(created_at: :desc)
    @topics = Topic.page(params[:page]).per(3)
  end
  
  def new
    @topic = Topic.new
    @topic.user_id = current_user.id
    @topic.materials.build
  end

  def create 
   
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  # 詳細
  def show
    @topic = Topic.find(params[:id])
  end
  
  # 検索機能
    def search
    @topics = Topic.search(params[:search])
    end
  
  
  # 削除 
  def destroy
    # binding.pry
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path, success: '記事を削除しました'
  end
  
  # 計算
  def ajax_gram
    kekka = 0
    @topic = Topic.find(params[:topic_id]) 
    @ninnzuu = params[:ninnzuu]
    @gram = []
    @topic.materials.each do | m |
      kekka = @ninnzuu.to_i * m.gram.to_i
      @gram.push(kekka)
    end
    # binding.pry
    respond_to do |format|
      format.js
      format.html
    end
    
  end
  
  private
  def topic_params
    params.require(:topic).permit(:user_id, :image, :description, :title,:subject, materials_attributes: [:material, :gram])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
      def new
        @user = User.new
      end
      
      def create
        @user = User.new(user_params)
        if @user.save
          redirect_to root_path, success: '登録が完了しました'
        else
          flash.now[:danger] = "登録に失敗しました"
          render :new
        end
      end
            
      def show
      @user = User.find(params[:user_id])
      end      
              
     private
      def user_params
         params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">アドバイスを送る</h1>
        
        <%= form_for @comment do |f| %>


          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control' %>
            <%= f.hidden_field :topic_id, :value => @comment.topic_id %>
          </div>
          
          <% if logged_in? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>給食のサイト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        
        <span><%= link_to '[料理投稿サイト]' , root_path ,class: "navbar-brand"%></span>
        
        <!--検索機能-->
        <div class="search">
            <%= form_tag(search_path, :method => 'get') do %>
                <span class="text-white">料理名</span>
                  <%= text_field_tag 'search', nil, placeholder: '例　肉じゃが　カレー' %>
                  <%= submit_tag '検索',:name => nil %>
              <% end %>
        </div>
        <!--検索機能-->
        
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          
            <li>
              <%= link_to '「お気に入り」' , favorites_index_path %>
            </li>
            <li>
              <%= link_to '「レシピを書く」', new_topic_path %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
            
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>
      <script>
      $(function(){
      $(".alert").fadeOut(5000);
      });
      </script>
        <!--<= debug(params)if Rails.env.development? %>-->
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">料理サイト</h1>
    <h3 class="text-white">新しい投稿</h3>
<!--ここから-->

    <div style="height:350px; overflow-x:auto">
        <div calss="topic-index-single">
        <% @topics.each do |topic| %>
        <h4 class="text-white">料理名「<%=topic.title%>」</h4>
        <p><%= image_tag topic.image.url %></p>
        <% end %>
         </div>
         <% if logged_in? %>
          <div class="row">
          <div class="col-md-offset-5 col-md-2">
          <%= link_to 'もっと見る', topics_path, class: 'btn btn-block btn-white' %>
          </div> 
        </div>
        <% end %>
     </div>   
<!--ここまで-->
    <% if logged_in? %>
      <% else %>
          <div class="row">
            <div class="col-md-offset-3 col-md-3">
              <%= link_to 'Sign in', new_user_path, class: 'btn btn-block btn-white' %>
            </div>
            <div class="col-md-3">
              <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
            </div>
          </div>
    <% end %>
      </div>
</div>

app/views/topics/_ajax_gram.html.erb
<table class="table table-bordered">
          <thead>
             <tr>
              <th scope="col">材料名</th>
              <th scope="col">グラム</th>
              <th scope="col">人数分</th>
            </tr> 
        　</thead>
        　
          <tbody>
                <% i = 0 %>
                <% @topic.materials.each do |m|%>
                  <tr>
                    <td><%= m.material %></td>
                    <td><%= m.gram %></td>
                    <td><%= @gram[i] %></td>
                  </tr>
                  <% i += 1 %>
                <% end %>
            
          </tbody>
</table>

app/views/topics/_material_fields.html.erb
    <div id="input_pluralBox">
      <div class="input_plural">
        <div style="display:inline-flex">
          <div class="nested-fields">
            <%= f.label :材料名 %>
            <%= f.text_area :material %>
            <%= f.label :グラム %>
            <%= f.text_area :gram %>
            <%= link_to_remove_association "−", f ,class: 'btn btn-default'%>
           </div> 
        </div>
      </div>
    </div>

app/views/topics/_material_two_fields.html.erb
<div id="input_pluralBox">
      <div class="input_plural">
        <div style="display:inline-flex">
          
        </div>
      </div>
</div>

app/views/topics/ajax_gram.js.erb
$('#gram_hyouzi').html(
  '<%= escape_javascript(render :partial => 'ajax_gram') %>'
);

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h4 class="topic-author">
              投稿者「<%= topic.user.name %>」
             <p>料理名「<%=topic.title%>」</p>
             <p>業態 「<%=topic.subject%>」</p>
            </h4>
                <div class="pages">
                  <%= image_tag topic.image.url %>
                </div>
                
              <% if topic.favorite_users.include?(current_user) %>
                  <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                  <%= image_tag 'icons/heart.png', class: 'topic-index-icon-red' %> 
              <% end %>
              
              <% else %>
                  <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                  <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>           
             <% end %>
    <% end %>
            <%= topic.favorite_users.count %>
            <!-- コメント実装-->
            
              <%= link_to new_comment_path(topic_id: topic.id) do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
              <% end %>
               <!--詳細-->
              <%= link_to '[材料情報]', topic_path(topic.id), class: 'topic-index-icon' ,method: :get  %>
              
              <!--削除-->
              <%= link_to '[投稿削除]', topic_path(topic.id), topic_id: topic.id ,class: 'topic-index-icon' ,method: :delete%>
              <h4>作り方<h4>
            <p class="topic-text">
              <%= topic.description %>
              <p class="adobaisu">アドバイス一覧</p>
              <% topic.comments.each do |comment| %>
              <p>
             <li> <%= comment.content%></li>
              </p>
              <% end %>
              </p>
              
          </div>
        </div>
      </div>
    <% end %>
    <div class="pagenetion">
    <%= paginate @topics %>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">投稿画面</h1>
        
        <%= form_with model: @topic, local: true do |f| %>
        
          <%= f.hidden_field :user_id, value: @topic.user_id %>
          
          <div class="form-group">
            <%= f.label :料理名 %>
            <%= f.text_area :title, class: 'form-control' , size: "1x1"%>
          </div>
          
          <div class="form-group">
            <%= f.label :写真 %>
            <%= f.file_field :image%>
          </div>
          
          <div class="form-group">
            <%= f.label :業態 %>
            <p><%= f.select :subject, [["病院","病院"],
                                    ["保育園","保育園"],
                                    ["食堂","食堂"],
                                    ["レストラン","レストラン"],
                                    ["福祉施設","福祉施設"]],
                                    class: 'form-control' %>
            </p>
          </div>
          
          <!--材料-->
                  
                <div id="input_pluralBox">
                   <div class="input_plural">
                      <div style="display:inline-flex">
                        <%= f.fields_for :materials do |m| %>
                          <%= render "material_fields", f: m %>
                        <% end %> 
                          <%= link_to_add_association "＋", f, :materials ,class: 'btn btn-default' %>
                      </div>
                      
                      
                    </div>
                  
                </div>
          <!--材料-->
          <div class="form-group">
            <%= f.label :作り方 %>
            <%= f.text_area :description, class: 'form-control', size: "1x5"%>
          </div>
          
          <% if logged_in? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/search.html.erb
<div class="topic-index-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="topic-index-single">
                    <h2>検索結果</h2>
                    <% @topics.each do |topic| %>
                        <p>投稿者「<%= topic.user.name %>」</p>
                        <p> 料理名「<%=topic.title%>」</p>
                        <p>業態 「<%=topic.subject%>」</p>
                        <p><%= image_tag topic.image.url %></p>
                        
                        <div class="search-show">
                        <%= link_to '▶[材料情報]', topic_path(topic.id), class: 'topic-index-icon' ,method: :get  %>
                        </div>
                        
                        <hr size="3">
                        
                    <%end%>
                </div>
             </div>
        </div>
    </div>
</div>

app/views/topics/show.html.erb
<div class="topic-index-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="topic-index-single">
                    <div class="well">
                        <h2>材料ページ</h2>
                        <p>投稿者「<%= @topic.user.name %>」</p>
                        <p> 料理名「<%=@topic.title%>」</p>
                        <p>業態「<%=@topic.subject%>」</p>
                        
                        <!--追加-->
                    
                            
                        <h3>人数計算</h3>
                            <div id="request_ajax_update" >
                                <%= form_tag(ajax_gram_topics_path, method: :post, remote: true) { %>
                                  <%= hidden_field_tag :topic_id, @topic.id %>
                                  <%= text_field_tag :ninnzuu, nil, placeholder: '例  ○○人分' %>
                                  <%= submit_tag "計算"  %>
                                  <% } %>
                            </div>   
                            
                        <!--追加-->
                        <div id="gram_hyouzi">
                             <table class="table table-bordered">
                                  <thead>
                                     <tr>
                                      <th scope="col">材料名</th>
                                      <th scope="col">グラム</th>
                                      <th scope="col">人数分</th>
                                    </tr> 
                                　</thead>
                                　
                                  <tbody>
                                        <% @topic.materials.each do | m |%>
                                          <tr>
                                            <td><%= m.material %></td>
                                            <td><%= m.gram %></td>
                                            <td></td>
                                          </tr>
                                        <% end %>
                                    
                                  </tbody>
                            </table>
                        </div>
                            <div class="pages">
                            <p ><%= image_tag @topic.image.url %></p>
                            </div>
                     </div>      
                </div>
            </div>    
        </div>
    </div>
</div>

app/views/topics/test.html.erb
<%= form_with(model: @user) %>
  <%= f.text_field :sample1, id: "sample1" %>
  <%= f.text_field :sample2, id: "sample2" %>

  <%= f.text_field :result, id: "result" %>
<%end%>

<script>
$('#sample2').change(function() {
  var s = $(#sample1).val();
  var a = $(#sample2).val();
  var si = parseInt(s);
  var sa = parseInt(a);

  var result = si - sa

  $('#result').val(result)
});
</script>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :名前, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :メール, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :パスワード, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :再パスワード, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>